# Site settings
title: Ryan Brownhill's Blog
email: ryanbrownhilldesign@gmail.com
description: "This is the blog of Ryan Brownhill's thoughts, resources and other adventures."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ryanbrownhill.github.io" # the base hostname & protocol for your site
twitter_username: ryan_brownhill
github_username:  ryanbrownhill
# Build settings
markdown: kramdown
